---
# action.yml
name: "Equinix Metal Deleter"
description: "The Equinix Metal Sweeper action deletes just one server within a project"
inputs:
  authToken:
    description: "Equinix Metal API Auth Token"
    required: true
  projectID:
    description: "Equinix Metal Project UUID"
    required: true
  runnerName:
    description: "Name of the runner to be deleted"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "trash-2"
  color: "green"
